[project]
name = "gpt-scraper"
version = "0.0.1"
description = "A scraper to log all publicly available ChatGPT conversations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "tqdm>=4.67.1",
    "tyro>=0.9.27",
    "waybackpy>=3.0.6",
]
